version: '3'

services: 
    wordpress:
        build: .
        restart: always
        ports: 
            - 8080:80
        environment: 
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: wpuser
            WORDPRESS_DB_PASSWORD: wppass
            WORDPRESS_DB_NAME: wpdb
            XDEBUG: true
        volumes: 
            - ./plugins:/var/www/html/wp-content/plugins/meu-plugin
            - ./src:/var/www/html/wp-content/themes/meu-tema

    db:
        image: mysql:5.7
        restart: always
        environment: 
            MYSQL_DATABASE: wpdb
            MYSQL_USER: wpuser
            MYSQL_PASSWORD: wppass
            MYSQL_RANDOM_ROOT_PASSWORD: '1'
        volumes: 
            - db:/var/lib/mysql

    # Email falso para testes de envio de email
    mailhog:
        image: mailhog/mailhog
        ports: 
            - 1025:1025
            - 8025:8025

    # Alternativa para o phpmyadmin
    # adminer:
    #     depends_on: 
    #         - db
    #     image: adminer
    #     restart: always
    #     ports: 
    #         - 8888:8080

    phpmyadmin:
        depends_on: 
            - db
        image: phpmyadmin
        restart: always
        ports: 
            - 8888:80

networks: 
    back:
        
volumes: 
    db: